[Fusion\Palette]
Window=#000000
WindowText=#ffffff
Base=#0a0a0a
AlternateBase=#111111
ToolTipBase=#111111
ToolTipText=#00e5ff
PlaceholderText=#546e7a
Text=#ffffff
Button=#111111
ButtonText=#ffffff
BrightText=#ffffff
Highlight=#e040fb
HighlightedText=#000000
Link=#00e5ff
LinkVisited=#e040fb
